apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-csi-gp2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp2  # ou 'gp3' se desejar o novo tipo de volume do EBS
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-csi-gp2
  resources:
    requests:
      storage: 10Gi
