services:
  backend:
    build:
      context: ./
    environment:
      - FLASK_APP=run.py
      - FLASK_DB_TYPE=postgres
      - FLASK_DB_USER=postgres
      - FLASK_DB_NAME=guess_game_db
      - FLASK_DB_PASSWORD=secretpass
      - FLASK_DB_HOST=db
      - FLASK_DB_PORT=5432
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${FLASK_DB_USER:-postgres}    # Usuário do PostgreSQL
      POSTGRES_PASSWORD: ${FLASK_DB_PASSWORD:-secretpass}  # Senha do PostgreSQL
      POSTGRES_DB: ${FLASK_DB_NAME:-guess_game_db} 
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
